### PR TITLE
use the Api for the reservations

### PR DESCRIPTION
**Pull request by JuanLugoS**
The usage of the API allows the back add the reservations too the users
imagen
Send confirmation emails
imagen
and Calculate the cost based on the data stored
imagen

### CODE REVIEW

**Review by Crola1702 — CHANGES_REQUESTED** [review]
No. API is not reliable for reservation process (nor any process in the App)

**Comment by JuanLugoS** [comment]
> No. API is not reliable for reservation process (nor any process in the App)

Reliability is not quite accurate to the process of creating a reservation but not adding its uid to a the user

**Comment by Crola1702** [comment]
For simplicity, one should make a query to the reservations collection and filter all documents by user id (the time of this operation can be improved by using an index, for example).

Saving each reservation in the user collection could lead to inconsistencies, as the data is duplicated

You can read more about it here: https://firebase.google.com/docs/firestore/query-data/queries

**Comment by Crola1702** [comment]
Closing as this is not present in the roadmap

**Pull request closed without merging**
