### PR TITLE
added QR code to ongoing reservations

### PR DESCRIPTION
**Pull request by JuanLugoS**
Added QR code: stored in local storage and then generated. #49 
The QR code when scanned activates the reservation changing its status

Imagen de WhatsApp 2023-12-01 a las 22 58 33_ea908680

### CODE REVIEW

**Comment by JuanReyes01** [comment]
The QR code must be on the active reservation view

**Comment by JuanLugoS** [comment]
Closed #50

**Comment by JuanLugoS** [comment]
Close #49

**Comment by JuanLugoS** [comment]
added quick look to last reservation made

Imagen de WhatsApp 2023-12-04 a las 18 43 58_fadaa794

waiting for @JuanReyes01 review

**Review by JuanReyes01 — APPROVED** [review]

**Pull request merged**
